### PR TITLE
fix the logic error on isNotPassing

### PR DESCRIPTION
**Pull request by chenghuang-mdsol**
This is to fix
https://github.com/rndsolutions/trx-merger/issues/14
I'm not sending the pr to trx-merger since it's not maintained anymore.

### CODE REVIEW

**Comment by chestercodes** [comment]
Thanks for PR, looks good but I'll need to look at it properly over the weekend as I think the code currently always outputs "Failed" at the moment.

**Comment by chenghuang-mdsol** [comment]
> Thanks for PR, looks good but I'll need to look at it properly over the weekend as I think the code currently always outputs "Failed" at the moment.

Yea. the code needs some change. The error is probably because the code is expecting ResultSummary.outcome 's value to be 'Passed' or 'Failed'.
The actual case might be 'Completed' instead of 'Passed'.
A better logic would be counting the failed and errored tests instead of aggregate ResultSummary.outcome

See this real trx:
image

**Comment by chenghuang-mdsol** [comment]
fixed ResultSummary.Outcome too

**Review by chestercodes — APPROVED** [review]

**Comment by chestercodes** [comment]
I've merged that and made a version 1.0.0 should be available from nuget shortly.

**Pull request merged**
